"""A small seeded lead dataset for the technical-test demo."""

SAMPLE_LEADS = [
    {
        "full_name": "Ana Marques",
        "email": "ana.marques@example.pt",
        "phone": "+351 912 000 111",
        "source": "meta_lead_ad",
        "budget_eur": 450_000,
        "financing_preapproved": True,
        "desired_location": "Lisbon — Príncipe Real",
        "property_type": "apartment",
        "timeline": "immediate",
        "notes": "Looking for a 2-bedroom with natural light, ready to move fast.",
    },
    {
        "full_name": "João Pereira",
        "email": "joao.pereira@example.pt",
        "phone": "+351 913 222 333",
        "source": "website_form",
        "budget_eur": 220_000,
        "financing_preapproved": True,
        "desired_location": "Cascais",
        "property_type": "apartment",
        "timeline": "3_months",
        "notes": "First-time buyer, flexible on exact location.",
    },
    {
        "full_name": "Sofia Costa",
        "email": "sofia.costa@example.pt",
        "phone": "+351 914 444 555",
        "source": "idealista",
        "budget_eur": 95_000,
        "financing_preapproved": False,
        "desired_location": "",
        "property_type": "",
        "timeline": "exploring",
        "notes": "Just browsing, no firm plans yet.",
    },
    {
        "full_name": "Miguel Santos",
        "email": "miguel.santos@example.pt",
        "phone": "+351 915 666 777",
        "source": "referral",
        "budget_eur": 780_000,
        "financing_preapproved": True,
        "desired_location": "Sintra",
        "property_type": "house",
        "timeline": "immediate",
        "notes": "Relocating from abroad, wants a family home with garden.",
    },
]
